### ISSUE TITLE
Add support to python 3

### ISSUE THREAD

**Issue by nividic** [MobleyLab/Lomap#1]
The code must support python 3 as well

**Comment by nividic** [comment]
I started adding support to python 3. The graph generation function presents some problems to overcome

**Comment by davidlmobley** [comment]
Excellent. When we do this we should also get the Travis-CI testing working for Python 3.

**Comment by ppxasjsm** [comment]
Travis is testing for python 3.5 and 3.6 currently and works fine. 2.7 should really be no longer supported. I don't think this  a problem since there wasn't a proper versioned release other than a somewhat unversioned conda packaged.
