### ISSUE TITLE
Allowing different charges in the network graph

### ISSUE THREAD

**Issue by cgorgulla** [MobleyLab/Lomap#10]
Lomap seems to connect molecules only if they have the same charges.

However, I do need to connect also molecules with different charges for experimental purposes. How is it possible to disable this restriction? (I am aware that it is recommended not to do change charges in alchemical free energy simulations.)

**Comment by davidlmobley** [comment]
@nividic - this would be good to answer and document. Perhaps there should also be an option to enable this via some sort of "expert" mode which comes with lots of disclaimers. I can see this being something which our group might need to do down the road as well. Also, if dealing with the requisite charge corrections becomes something easier to do in common simulation packages, people will want to move in this direction, so making it possible (but not easy) to do this now would set us up for that if it happens.

**Comment by davidlmobley** [comment]
@nividic - for the record, I know you did some work on this, but did it make it into the repo? Or is this still something to do later?

**Comment by nividic** [comment]
This has been fixed. The user can manually select an electrostatic charge scoring value in the range [0,1] to be used when molecules have different charges. In this case the produced graph will result connect. The user can input the desired score by passing the keyword ecrscore=value to the molecule database as follows:

``lomap.DBMolecules("python string pointing to a directory with mol2 files", output=True, ecrscore=0.1)
``

 where ecrscore is the selected value to use when molecules have different total charges.
