### ISSUE TITLE
Network figure can have bad resolution

### ISSUE THREAD

**Issue by cgorgulla** [MobleyLab/Lomap#11]
Another minor issue is the resolution of the image in PNG format which is drawn by the method graphen.draw()

The image which is produced is very nice and useful, but in my applications the quality of the image is relatively poor, e.g. the labels are almost unreadable. This is the case both when displaying the figure and saving the figure with the command 

`            plt.savefig('graph.png', facecolor=fig.get_facecolor())
`

I have played with the numerous image parameters in that function, but the required choice is not obvious too me and seems non-trivial.

**Comment by nividic** [comment]
Hi, I'm going to check if it is easy to produce a high quality .png file. You can also use another software package to visualize the graph e.g. Gephi but you have to work out how to visualize the molecule depictions on the graph nodes starting from the produced molecule list.

**Comment by nividic** [comment]
I fixed this generating a .ps file containing all the molecule depictions. However, there is a bug in graphviz and the generated .ps  doesn't seem to follow the correct Adobe-PS standard. I can also generate a .png file. I'm going to file a bug tracker to the graphviz developers

**Comment by davidlmobley** [comment]
OK, @nividic - I'd get the fix in so it will generate a ps file once the graphviz bug is fixed, and if you can generate a better png that will serve in the short term.

**Comment by davidlmobley** [comment]
@nividic - this is fixed, right? If so please mark as closed.

**Comment by nividic** [comment]
A produce .png file has been generated. The ideal was to create a vectorial image but unfortunately graphviz seems to have compatibility problems with the produced .ps file. As a consequence an improved version the .png file was adopted
