### ISSUE TITLE
Update to not pin to specific PyQt4 versions

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/Lomap#12]
We've had to pin to a specific PyQt4 version, as well as certain specific versions of other software, because of API changes. When someone is back on developing this in more detail, we should bring things up to the more current versions.

**Comment by nividic** [comment]
I would like to make this change when python3 will be supported. It is not difficult to change to PyQt5 I need to change just a line in the code.

**Comment by davidlmobley** [comment]
Sounds good to me. This was just a placeholder so that you or whoever else ends up working on this later would remember to revisit it. :)

**Comment by ppxasjsm** [comment]
I'll try and pick this up if I can.

**Comment by ppxasjsm** [comment]
It seems a bit silly to have a whole pyqt5 dependency only to acquire the sceen resolution. Instead will be using xdpyinfo removing any kind of qt dependency. This was done with commit cfba8e0.
