### ISSUE TITLE
Handle chirality

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/Lomap#13]
Due to difficulties with maximal common substructures and chirality, LOMAP currently deals with chiral centers in a rather extreme manner -- specifically, the chiral center is deleted before doing the mapping, then only the largest fragment of the resulting molecule is retained. While this "works" (it produces mappings that are valid) in the cases of larger molecules with chiral centers in the middle of a scaffold, it will result in extreme transformations even when such transformations are not needed.

Chirality handling will need to be updated carefully, probably by modifying the MCSS search to be chiral and/or using coordinate information to identify which stereoisomer is being considered and include this when selecting which match to use.

**Comment by halx** [comment]
The Open3DALIGN algorithm (https://doi.org/10.1007/s10822-011-9462-9) may be of use here (implemented in RDKit as GetO3A).  We have done some tests and so far they look quite encouraging.

**Comment by ppxasjsm** [comment]
Is chirality supported or was this never implemented?

**Comment by davidlmobley** [comment]
This has not been done. It's complex. I can discuss in a call if you'd like. If you're going to grow in a chiral center you may even need to use restraints to keep it in the chirality you want.

**Comment by davidlmobley** [comment]
It's possible Silicon has done something about this. @shuail ?

**Comment by davidlmobley** [comment]
This is another thing that @richardjgowers and team might need to look at at some point. Richard, I should fill you in in a call.
