### ISSUE TITLE
Re-license under MIT

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/Lomap#15]
@nividic - I see that for some reason we have this under GPL currently. Any issues with me switching it to MIT? @shuail , we also need your input as you've contributed to this.

@halx - I don't think any of your code is in here yet but I probably should get your input too.

**Comment by nividic** [comment]
No problem at all

**Comment by shuail** [comment]
Good for me

**Comment by halx** [comment]
I'm fine with this too.
