### ISSUE TITLE
add the radial option in graphing

### ISSUE THREAD

**Issue by shuail** [MobleyLab/Lomap#22]
I add the radial graphing options (the commit in shuaidev in 07/11). The idea is that if we have a lead compounds and the rest compounds are derivatives from the lead compounds, we want to have direct calculations from all derivatives to this lead compound and also create a cycle in between the derivatives. So the layout is similar to a bicycle and we name this option as radial option. I made changes to the code to have two radial options below:

The Complete radial option will pick the radial center (lead compound) automatically by the structure similarity: the ligand shared the most structural similarity with others will be picked as lead compound. 

The Biased radial option will take the custom specified compound as the lead compound.

**Comment by davidlmobley** [comment]
Closed by #18
