### ISSUE TITLE
Include substantial test set, output graphics

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/Lomap#25]
@shuail - the different mapping options would be a lot easier to explain/document if we could provide output mappings illustrating them. It would be a lot easier to do THAT if we had a substantial test set in here. Do you guys have one you're using which could actually be deposited in the repo? Maybe we should be using the "JACS" set from Schrodinger and deposit the ligands here? Thoughts?

**Comment by shuail** [comment]
@davidlmobley yes, sounds good to me. Just commit an example code: example_radial_graph.py and a folder named radial under the test folder. The code will use the data from radial folder and generate a radial graph. It's the Tyk2 target from the "JACS" paper.
