### ISSUE TITLE
Installing lomap via mobleylab conda channel

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#36]
Hi,

I am trying to use the conda install of lomap from the Mobley lab channel is this still a valid way to install things? 
I find it quite worrying that conda can simply downgrade my python from 3.5 to 2.7:
```
The following packages will be DOWNGRADED:

    python:                        3.5.5-h5001a0f_2      conda-forge --> 2.7.15-h43f7c74_0 conda-forge
```
If you don't know what you are doing this may mess with your conda environments quite badly.

**Comment by davidlmobley** [comment]
That's not good. Probably we need to work on our conda builds, but it will take me some time to get to this. I suggest installing from source in the meantime. You perhaps also want to try out the code avaialble in #34 .

**Comment by ppxasjsm** [comment]
I installed from source and am happy to switch to #34.

**Comment by davidlmobley** [comment]
OK, try it out and let us know if it seems like it improves the situation; @shuail  and I have both been tied up with other things and haven't been able to invest much effort on this in a while but if it seems to be helping we can try to get it merged in sooner.

**Comment by nitroamos** [comment]
@ppxasjsm were you able to get it to work?

I've been asked to look into `lomap` for my project so I'm interested in advice on the best approach.

**Comment by ppxasjsm** [comment]
I have installed the networkx2 branch of lomap successfully. 

Been testing bits of it since. No massive issues, apart from it running quite slowly on large number of compounds and been adding some network plotting bits to my scripts.

**Comment by davidlmobley** [comment]
Great. So you think that PR is ready to merge?

We welcome any contributions back you would like to make. :)

**Comment by davidlmobley** [comment]
@ppxasjsm - did you think #34 should be merged? Is that the brnach you're working from?

**Comment by ppxasjsm** [comment]
I am working on the networkxd2 branch. I haven't run into any major issues currently. I did change the network visualisation to just compound names on the nodes rather than drawing the structures as they are not displayed in a way that is useful. If I have time I can add bits to this towards the end of the week, if that is useful and can give a proper feedback. Mostly been trialing the perturbation map generation for the current D3R challenge, but happy to make some contributions.

**Comment by davidlmobley** [comment]
OK, that sounds great, @ppxasjsm . Thanks!

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
