### ISSUE TITLE
Enhacement questions

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#39]
Hi,

would it make sense to add some of these enhancements?

1. automatic versioning using something like versioneer
2. switch to pytest rather than nose
3. offer a pypi install rather than the outdated conda?

In terms of coding style there seems quite a vast mix of camelcase and python style naming of functions. Would it make sense to make this more uniform?

**Comment by davidlmobley** [comment]
We definitely want versioneer and pytest.

Ideally we'd have pypi and (current) conda installs.

**Comment by davidlmobley** [comment]
Also, would make sense to have style be more uniform as well.

**Comment by ppxasjsm** [comment]
I can probably add most of these, if that helps?

**Comment by davidlmobley** [comment]
That would be awesome. As I may have said before I don't currently have anyone working on this and most of my effort is tied up with the force field initiative and SAMPL organization at the moment. I feel bad I'm not contributing anything here and am worried it will wither without my attention but haven't sort out how I can find the time to assist. :)

**Comment by davidlmobley** [comment]
Have you seen the cookiecutter stuff from the Chodera lab which is now at MolSSI?

**Comment by ppxasjsm** [comment]
yep. I have seen cookiecutter. To use this resetting up the project would be the easiest I guess and just add the code and make changes where necessary?

**Comment by davidlmobley** [comment]
I'm not sure I can answer that without drilling into it a little bit; it could also be that pulling the cookiecutter stuff down and copying it into this would not be hard and might involve less git wrangling. I'm OK with either. Let me know if you have preferences and if you need anything from me.

**Comment by ppxasjsm** [comment]
I can easily add things to the repository, without the cookiecutter, but just taking elements from it. Don't think I need anything. I'll add things to the fork I created and will make a pull request. Unless you think it is easier for me to have access to the repo directly.

**Comment by davidlmobley** [comment]
I'll give you acccess now.

**Comment by ppxasjsm** [comment]
Thanks!

**Comment by ppxasjsm** [comment]
I still seem to not be able to push to the repository:

```ERROR: Permission to MobleyLab/Lomap.git denied to ppxasjsm.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by davidlmobley** [comment]
You have to accept the invite first, see https://github.com/MobleyLab/Lomap/invitations , @ppxasjsm .

**Comment by ppxasjsm** [comment]
Great thanks! Sorry I hadn't seen the invitation.

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
