### ISSUE TITLE
Problem specifying the hub molecule

### ISSUE THREAD

**Issue by achantzis** [MobleyLab/Lomap#42]
Dear all,

I am running lomap on a set of molecules and it runs fine using python 2.7. I have the following problem though: when I try to specify the hub molecule, so as to estimate the similarity scores of all the rest of the molecules with respect to the hub molecule I do not get the desired results. The output is the same graph as the one I get without specifying the hub option. I use the following command:

lomap -v pedantic -b system_01.mol2 -a ~/molecules/test

Can anyone please tell me what might be the problem?

Sincerely,

Agisilaos

**Comment by davidlmobley** [comment]
That's odd. @shuail ??

(He added the hub option recently.)

**Comment by shuail** [comment]
@achantzis That's odd, could you try to run the test case under the tests folder (the function is here https://github.com/MobleyLab/Lomap/blob/49152deeb5e70c64b8d9906fc76df2b28c404b67/test/test_lomap.py#L140 ) and see if you could get the radial graph using that example case?

**Comment by achantzis** [comment]
@shuail I have run the test script as: python ./test_lomap.py 

And I get the following:

.usage: LOMAPv1.0 [-h] [-p PARALLEL] [-v {off,info,pedantic}] [-t TIME]
                 [-e ECRSCORE] [-o] [-n NAME] [-d] [-m MAX] [-c CUTOFF] [-r]
                 [-b HUB] [-f] [-a]
                 directory
LOMAPv1.0: error: argument -p/--parallel: invalid int value: '-1.5'
usage: LOMAPv1.0 [-h] [-p PARALLEL] [-v {off,info,pedantic}] [-t TIME]
                 [-e ECRSCORE] [-o] [-n NAME] [-d] [-m MAX] [-c CUTOFF] [-r]
                 [-b HUB] [-f] [-a]
                 directory
LOMAPv1.0: error: argument -v/--verbose: invalid choice: 'err_option' (choose from 'off', 'info', 'pedantic')
usage: LOMAPv1.0 [-h] [-p PARALLEL] [-v {off,info,pedantic}] [-t TIME]
                 [-e ECRSCORE] [-o] [-n NAME] [-d] [-m MAX] [-c CUTOFF] [-r]
                 [-b HUB] [-f] [-a]
                 directory
LOMAPv1.0: error: argument -t/--time: invalid int value: '-1.5'
usage: LOMAPv1.0 [-h] [-p PARALLEL] [-v {off,info,pedantic}] [-t TIME]
                 [-e ECRSCORE] [-o] [-n NAME] [-d] [-m MAX] [-c CUTOFF] [-r]
                 [-b HUB] [-f] [-a]
                 directory
LOMAPv1.0: error: argument -m/--max: invalid int value: '-5.0'
usage: LOMAPv1.0 [-h] [-p PARALLEL] [-v {off,info,pedantic}] [-t TIME]
                 [-e ECRSCORE] [-o] [-n NAME] [-d] [-m MAX] [-c CUTOFF] [-r]
                 [-b HUB] [-f] [-a]
                 directory
LOMAPv1.0: error: argument -m/--max: invalid int value: 'string'
..........
----------------------------------------------------------------------
Ran 11 tests in 15.264s

OK

It seems that the tests for invalid arguments have passed and all is fine. I did not get any graph out of this run though... Was it expected to produce a graph by running the tests of this script?

**Comment by ppxasjsm** [comment]
@achantzis are you on the master branch or the networkx2 one? Can you type `git log` in your terminal? You may just not be using a branch where that functionality is already implemented?

**Comment by achantzis** [comment]
@ppxasjsm 

Doing git log I got the following:

commit f0d52a1e7ea11a9ef5bff168db39a7561c8ac9f6
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 22:30:39 2018 +0100

    only build for devel and master

commit 9e97a08bb74567c35f11e191115b0c08a75a60af
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 22:22:13 2018 +0100

    adding pygraphviz

commit dba977b5882f4af0018602e62024235ecc4c44c8
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 22:16:23 2018 +0100

    matplotlib 1.5

commit 787f1ba10494767479371de8f4bf401ee8a1e878
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 22:11:01 2018 +0100

    welcome to conda dependency hell

commit d61ab1bbffe0c91b7e577b98529c4cf49d76eab0
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 21:56:01 2018 +0100

    adding pyqt4 dependcy to travis

commit fe3bd91cc9b60a62ec19f3b030f3f41106820399
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 17:35:56 2018 +0100

    are you a valid yml?

commit 67ee93595bf5107772cc82315f30989144e7ee8f
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 17:28:58 2018 +0100

    are you a valid yml?

commit 7d5a346bcd89f169ece4fa4fc4bf5b0cd58fcbfe
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 17:02:45 2018 +0100

    ugh travis again

commit fa24ec78fb53e705f450ede8288b9dc4b062cb03
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 17:00:43 2018 +0100

    ugh travis

commit 20e1a551a2fc0cf1332d439cfc9b67d878593b2d
Author: ppxasjsm <antonia.mey@fu-berlin.de>
Date:   Tue Oct 16 16:58:22 2018 +0100

    fixing Pep* convention and trailing whitespaces issue

commit 7f3ace4888b07fd5f6201fd12cd4250728009680

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
