### ISSUE TITLE
MCS test fails with most recent version of rdkit

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#44]
The test for MCS passes with RDKIT version 2018.03, but fails with version 2018.09. Something worth investigating. 

For now, I'd suggest dependency of rdkit<=2018.03

**Comment by davidlmobley** [comment]
Sounds reasonable to pin to that for now and yes, we'll need to investigate.

cc @nividic who I think may be starting to need this soon too. :)

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
