### ISSUE TITLE
Colouring code for connecting compounds in FEP

### ISSUE THREAD

**Issue by achantzis** [MobleyLab/Lomap#45]
Dear all,

I would like to ask whether there is a reason that the graph produced by lomap sometimes contains molecules connected by light cyan lines and sometimes by red likes. Despite my efforts, I could not find any document mentioning this difference.

Best,

Agisilaos

**Comment by ppxasjsm** [comment]
Can you upload an example of the two different colour codings and how you run the code? Do you run it in the same way?

**Comment by achantzis** [comment]
Unfortunately I cannot upload the graph I am talking about because the data is classified. I will try to find some other example that has the same behaviour. I will update you ASAP.

Thank you!

**Comment by achantzis** [comment]
In the meantime I would like to know the following, if possible: the difference in colours exist in the out.eps file. In the out.dot file the compounds are connected with a regular grey line. 

Is there a mechanism that gives differ colours in the out.eps based on some metric?

Best,

Agisilaos

**Comment by ppxasjsm** [comment]
Hi @achantzis,

I just had a bit of a deeper look in the code. Basically, the red edges come from the strict similarity condition, whereas the cyan ones from a loose one. I think the original publication describes this well.  Have a look here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3837551/

I guess the reason why the .dot file does not contain the colours might because it does not support this, but I may be wrong about this.

**Comment by achantzis** [comment]
Thank you @ppxasjsm 

I appreciate your feedback and help. I have read the paper you have mentioned but obviously I did not remember the classification in terms of the colour. I will go through it again.

Best,

Agis

**Comment by davidlmobley** [comment]
That would have been my guess as well -- strict vs loose scoring. In general you would prefer edges that use strict scoring but if you can't get such edges then you'd have to use loose scoring.

@nividic we should get this documented when updating.

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
