### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#47]
This is a wishlist of what features I would find useful in LOMAP [currently incomplete will expand in the next couple of days]:

- When a network is drawn keep molecules with the same orientation for the MCS (See attached image, where even the same groups are pictured in different ways)
![out](https://user-images.githubusercontent.com/3668316/48860141-f4672a80-edb7-11e8-83b4-370c52ab8723.png)
- Rather than using Node ID give a node the ID of the filename. Then I don't have to go back to the text file that contains the dictionary of the node ID and filename mapping. 
- write out edges that are in a csv style, i.e. filename, filename. The additional information with regard to similarity etc is also useful, however, If I want to quickly generate perturbations based on mol2 files I just need a list of edges that are dependent on filenames.  
- I would like easy incorporation with BioSimSpace, so we can use an automated generation of mappings. Currently, about 50% of the autogenerated mappings are unlikely to work in a free energy code, see issue #46. 

What would be really cool:
have an output that could be run in some kind of interactive network display environment (Javascript?), where only on click on nodes expand and you can see the structure otherwise only filenames and maybe similarity scores are displayed.

**Comment by nividic** [comment]
@ppxasjsm These are all good ideas that should be integrated with the large refactoring. It is also possible to generate interactive plots by using SVG (javascript based) files.

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap.
