### ISSUE TITLE
Rule mncar does not make any sense

### ISSUE THREAD

**Issue by halx** [MobleyLab/Lomap#5]
The central bit of the rule is

scr_mncar = float((nha_mcs_mol >= ths) or (nha_moli + 3) or (nha_molj + 3))

where the variables are number of atoms and as such either positive integers or zero.  ths is a threshold value and 4 by defaults  This means that the first expression is either True or False.  If it is False the second expression will be evaluated and will be a positive integer.  As such the third expression will never be evaluated.

So in sum, scr_mncar will be either 1.0 or float (nha_moli + 3).

What's the point of that?

**Comment by davidlmobley** [comment]
@nividic - can you check against the earlier implementation? Possibly we have a typo here?

(What are the variable names? I think I would recall what the logic is, but as there have been several generations of code since I worked on it, I don't know what the variable names are.)

**Comment by nividic** [comment]
I checked the original code and you are right. I did not correctly implemented the rule. An extract of the original code states:

``` python
        num_atom_mcs  = KBASE.ask( kwarg["mcs_id"], "num_heavy_atoms" )
        num_atom_mol0 = len( KBASE.ask( id0 ).heavy_atoms() )
        num_atom_mol1 = len( KBASE.ask( id1 ).heavy_atoms() )

        return float( (num_atom_mcs  >= self._threshold    ) or
                      (num_atom_mol0 <  self._threshold + 3) or
                      (num_atom_mol1 <  self._threshold + 3) )
```

Therefore the correct implementation  should be:

``` python
scr_mncar = float((nha_mcs_mol >= ths) or (nha_moli  <  ths + 3) or (nha_molj <  ths + 3))
```

In my implementation the prefix "nha" means number heavy atoms and "ths" is the threshold
