### ISSUE TITLE
Developper guide as a wiki page?

### ISSUE THREAD

**Issue by ppxasjsm** [MobleyLab/Lomap#50]
Everyone good with using a wiki page on github for the developer guide?

**Comment by davidlmobley** [comment]
I'm OK with that if it makes things way easier, though in general I have a preference for things under version control.

**Comment by ppxasjsm** [comment]
Can just use a markdown file instead also fine.

**Comment by nividic** [comment]
@ppxasjsm What do exactly mean for a developer guide?

**Comment by davidlmobley** [comment]
@nividic it's a discussion of how developers can/should get involved, what standard to conform to, etc. Check out `alchemlyb` for an example, perhaps.

**Comment by davidlmobley** [comment]
Closing this; maintenance moved to github.com/OpenFreeEnergy/Lomap. Hopefully @dwhswenson and @richardjgowers and team have a plan for docs over there.
